name: Run Arxiv Sanity Bot

on:
  schedule:
    # Run every hour
    - cron: "13 * * * *"

  workflow_dispatch:

jobs:
  run_arxiv_sanity_bot:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Randomly quit workflow
      run: |
        # Generate a random number between 1 and 13
        rand=$(($RANDOM % 19 + 1))
        echo $rand
        
        # If the number is not 1, exit without doing anything
        if [ "$rand" -ne 1 ]; then
          echo "Skipping workflow execution."
          #exit 1
        fi

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Cache parquet dataframe of processed abstracts
      uses: actions/cache@v3
      with:
        key: |
          arxiv-sanity-bot-cache-${GITHUB_RUN_ID}-${GITHUB_JOB}-${GITHUB_RUN_NUMBER}
        restore-keys: |
          arxiv-sanity-bot-cache
        path: |
          posted_abstracts.parquet
          ~/.cache/pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run Arxiv Sanity Bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DISCORD_ACCESS_TOKEN: ${{ secrets.DISCORD_ACCESS_TOKEN }}
      run: |
        arxiv-sanity-bot
